################################################################################

include ../../makefiles/help.mk
include ../../makefiles/functions.mk

################################################################################

print_tool_version_bash:
	$(call print_tool_version,bash,bash)

print_tool_version_make:
	$(call print_tool_version,make,make)

################################################################################
