name: make-ci

on:
  push:
  schedule:
    - cron: '0 0 * * *'
  workflow_call:

jobs:
  make-ci:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install deps (if `make deps-install` target exists)
        run: |
          if make -n deps-install 2>/dev/null; then
            make deps-install
          fi
      - name: CI
        run: make ci
